config/routes.rb
Rails.application.routes.draw do
  root to: 'todos#index'
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    todo = Todo.find(params[:id])
    todo.update!(todo_params)
    redirect_to todos_url, notice: "タスクを更新しました。"
  end

  def destroy
    todo = Todo.find(params[:id])
    todo.destroy
    redirect_to todos_url, notice: "タスクを削除しました。"
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
	    redirect_to todos_path, notice: "タスクを登録しました。"
    else
      render :new, notice: "タスクを入力してください。"
 #   todo.save!
 #   redirect_to todos_url, notice: "予定「#{todo.name}」を登録しました。"
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :description, :place, :deadline, :deadtime)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Todolist 
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield

app/views/todos/edit.html.slim
h1 todoの編集

.nav.justify-content-end
  = link_to '一覧へ戻る', todos_path, class: 'btn btn-secondary mr-5'

= form_with model: @todo, local: true do |f|
  .form-group.col-5
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'todo_name'
  .form-group.col-5.mt-1
    = f.label :description
    = f.text_field :description, class: 'form-control', id: 'todo_description'
  .form-group.col-4.mt-1
    = f.label :deadline, class: 'control-label'
    = f.date_field :deadline, class: 'form-control', id: 'todo_deadline'
  .form-group.col-4.mt-1
    = f.label :deadtime, class: 'control-label'
    = f.time_select :deadtime, class: 'form-control', id: 'todo_deadtime'
  .form-group.col-5.mt-1
    = f.label :place, class: 'control-label'
    = f.text_field :place, class: 'form-control', id: 'todo_place'


  = f.submit nil, class: 'btn btn-primary mt-3'

app/views/todos/index.html.slim
h1 todo一覧

= link_to 'todo登録', new_todo_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Todo.human_attribute_name(:name)
      th= Todo.human_attribute_name(:deadline)
      th= Todo.human_attribute_name(:deadtime)
      th= Todo.human_attribute_name(:place)
  tbody
    - @todos.each do |todo|
      tr
        td= link_to todo.name, todo
        td= todo.deadline
        td= l todo.deadtime
        td= todo.place
        td
          = link_to '編集', edit_todo_path(todo),  class: 'btn btn-primary'
          = link_to '削除', todo, method: :delete, data: { confirm: "タスクを削除します。よろしいですか？" }, class: 'btn btn-danger ms-1'

app/views/todos/new.html.slim
h1 todo登録

.nav.justify-content-end

  = link_to '一覧へ戻る', todos_path, class: 'btn btn-secondary mr-5'

= form_with model: @todo, local: true do |f|
  .form-group.col-5
    = f.label :name
    = f.text_field :name, class: 'form-control',id: 'todo_name'
  .form-group.col-5.mt-1
    = f.label :description
    = f.text_field :description, class: 'form-control', id: 'todo_description'
  .form-group.col-2.mt-1
    = f.label :deadline, class: 'control-label'
    = f.date_field :deadline, class: 'form-control'
  .form-group.col-4.mt-1
    = f.label :deadtime, class: 'control-label'
    = f.time_select :deadtime, class: 'form-control'
  .form-group.col-5.mt-1
    = f.label :place, class: 'control-label'
    = f.text_field :place, class: 'form-control'
  = f.submit nil, class: 'btn btn-primary mt-3'

app/views/todos/show.html.slim
h1 予定の詳細

.nav.justify-content-end
  = link_to '一覧へ戻る', todos_path, class: 'btn btn-secondary mr-5'

table.table.table-hover
  tbody
    tr
      th= Todo.human_attribute_name(:name)
      td= @todo.name
    tr
      th= Todo.human_attribute_name(:description)
      td= @todo.description
    tr 
      th= Todo.human_attribute_name(:deadline)
      td= @todo.deadline
    tr
      th= Todo.human_attribute_name(:deadtime)
      td= l @todo.deadtime
    tr
      th= Todo.human_attribute_name(:place)
      td= @todo.place

= link_to '編集', edit_todo_path, class: 'btn btn-primary mr-3'
= link_to '削除', @todo, method: :delete, data: { confirm: "予定「#{@todo.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger m-3'